// Copyright (c) Meta Platforms, Inc. and affiliates.

/**
 * @file theme build command — Compile a defineTheme file to CSS
 *
 * Takes a theme file that uses defineTheme() and outputs:
 * - A CSS file with token overrides and component styles
 * - An updated JS module that references the built className
 *
 * Usage:
 *   npx xds theme build ./src/themes/ocean.ts
 *   npx xds theme build ./src/themes/ocean.ts --out ./dist/ocean.css
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import {pathToFileURL, fileURLToPath} from 'node:url';
import {createJiti} from 'jiti';
import {getRunPrefix} from '../utils/package-manager.mjs';
import {sanitizeName, PathSafetyError} from '../utils/path-safety.mjs';
import {jsonOut, jsonError, humanLog} from '../lib/json.mjs';
import {cliError} from '../lib/cli-error.mjs';

// Import shared theme processing from core — ensures build and runtime
// use the same logic for typography.scale expansion, prose, and component rules.
let _defineTheme = null;
let _generateThemeRules = null;
let _generateThemeRulesSplit = null;
let _generateOnMediaCSS = null;
try {
  const coreTheme = await import('@xds/core/theme');
  _defineTheme = coreTheme.defineTheme;
  _generateThemeRules = coreTheme.generateThemeRules;
  _generateThemeRulesSplit = coreTheme.generateThemeRulesSplit;
  _generateOnMediaCSS = coreTheme.generateOnMediaCSS;
} catch (_e) {
  // Silent fallback. The theme command surfaces a clear error if it's actually
  // invoked without core being available; emitting a stderr warning at module-
  // load time would leak into every other command's output and break the
  // clean-stderr contract under --json (and breaks tests that assert it).
}

/**
 * Build a @generated attribution header for generated files.
 * @param {string} sourceFile - Relative path to the source theme file
 * @param {'css'|'js'|'ts'} lang - File language (determines comment syntax)
 * @param {string} [command] - The full CLI command used to generate this file
 */
function generatedHeader(sourceFile, lang = 'js', command) {
  const timestamp = new Date().toISOString();
  const body = [
    `@generated by \`xds theme build\` — do not edit manually.`,
    `Source: ${sourceFile}`,
  ];
  if (command) {
    body.push(`Command: ${command}`);
  }
  body.push(`Generated: ${timestamp}`);
  if (lang === 'css') {
    return `/*\n * ${body.join('\n * ')}\n */\n\n`;
  }
  return `/**\n * ${body.join('\n * ')}\n */\n\n`;
}

/**
 * Convert camelCase CSS property to kebab-case
 */
function toKebabCase(str) {
  return str.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);
}

/**
 * Convert a theme name to a valid JS identifier.
 * e.g. 'default-minimal' → 'defaultMinimal', 'ocean' → 'ocean'
 */
function toIdentifier(name) {
  return name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
}

/**
 * Convert a kebab-case component name to PascalCase.
 * e.g. 'button' → 'Button', 'progress-bar' → 'ProgressBar', 'avatar-status-dot' → 'AvatarStatusDot'
 */
function toPascalCase(name) {
  return name
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/**
 * Load known built-in values for a component's visual props from its .doc.mjs file.
 * Parses the type string (e.g. "'info' | 'warning' | 'error' | 'success'") to extract values.
 * Returns a map of { propName: string[] } for props that are visual (listed in theming targets).
 */
async function loadKnownValues(componentName) {
  // Resolve core src relative to the CLI package, not cwd (which may be a theme package)
  const cliDir = path.dirname(fileURLToPath(import.meta.url));
  const coreSrc = path.resolve(cliDir, '../../../core/src');
  if (!fs.existsSync(coreSrc)) return {};
  // Map component name to directory (e.g. 'banner' → 'Banner', 'dropdownmenu' → 'DropdownMenu')
  const dirs = fs.readdirSync(coreSrc, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);
  const dir = dirs.find(d => d.toLowerCase() === componentName.toLowerCase()
    || d.toLowerCase().replace(/[^a-z]/g, '') === componentName.toLowerCase());
  if (!dir) return {};

  const docPath = path.join(coreSrc, dir, `${dir}.doc.mjs`);
  if (!fs.existsSync(docPath)) return {};

  try {
    const docModule = await import(pathToFileURL(docPath).href);
    const doc = docModule.docs;
    if (!doc?.theming?.targets) return {};

    // Collect all props — from doc.props or doc.components[].props
    const allProps = [];
    if (doc.props) allProps.push(...doc.props);
    if (doc.components) {
      for (const comp of doc.components) {
        if (comp.props) allProps.push(...comp.props);
      }
    }
    if (allProps.length === 0) return {};

    // Collect visual prop names from theming targets
    const visualProps = new Set();
    for (const target of doc.theming.targets) {
      if (target.visualProps) {
        for (const vp of target.visualProps) visualProps.add(vp);
      }
    }

    // Extract values from prop type strings
    const result = {};
    for (const prop of allProps) {
      if (!visualProps.has(prop.name)) continue;
      if (!prop.type || typeof prop.type !== 'string') continue;

      // Parse union type: "'info' | 'warning' | 'error' | 'success'" → ['info', 'warning', 'error', 'success']
      const matches = prop.type.match(/'([^']+)'/g);
      if (matches) {
        result[prop.name] = matches.map(m => m.replace(/'/g, ''));
      }
    }
    return result;
  } catch {
    return {};
  }
}

// Cache for loaded known values
const _knownValuesCache = new Map();
async function getKnownValues(componentName) {
  if (!_knownValuesCache.has(componentName)) {
    _knownValuesCache.set(componentName, await loadKnownValues(componentName));
  }
  return _knownValuesCache.get(componentName);
}


/**
 * Generate TypeScript declaration file with module augmentation for custom
 * component prop values found in the theme's `components` keys.
 *
 * Scans component override keys (e.g. `status:neutral`, `variant:primary-muted`)
 * and generates augmentations for values not in the base type.
 *
 * Interface naming convention: XDS + PascalCase(component) + PascalCase(prop) + Map
 *   banner + status → XDSBannerStatusMap
 *   button + variant → XDSButtonVariantMap
 *
 * @param {object} themeDef - Theme definition (resolved by defineTheme)
 * @returns {string|null} TypeScript declaration content, or null if no augmentations needed
 */
function generateVariantDeclarations(themeDef) {
  if (!themeDef.components || Object.keys(themeDef.components).length === 0) {
    return null;
  }

  // Collect custom values: { component: { prop: [value, ...] } }
  const customValues = {};

  for (const [component, rules] of Object.entries(themeDef.components)) {
    for (const key of Object.keys(rules)) {
      if (key === 'base') continue;

      // Parse prop:value pairs from keys like 'status:neutral' or 'variant:primary+size:sm'
      const pairs = key.split('+');
      for (const pair of pairs) {
        const colonIdx = pair.indexOf(':');
        if (colonIdx === -1) continue;
        const prop = pair.slice(0, colonIdx);
        const value = pair.slice(colonIdx + 1);

        // It's a custom value — collect it for augmentation
        // (filtering against known values happens async in generateVariantDeclarationsAsync)
        if (!customValues[component]) customValues[component] = {};
        if (!customValues[component][prop]) customValues[component][prop] = new Set();
        customValues[component][prop].add(value);
      }
    }
  }

  // Sync stub — returns null, use generateVariantDeclarationsAsync instead
  return null;
}

/**
 * Async version of generateVariantDeclarations that reads known values from doc files.
 */
async function generateVariantDeclarationsAsync(themeDef) {
  if (!themeDef.components || Object.keys(themeDef.components).length === 0) {
    return null;
  }

  // Collect custom values: { component: { prop: [value, ...] } }
  const customValues = {};

  for (const [component, rules] of Object.entries(themeDef.components)) {
    const knownForComponent = await getKnownValues(component);

    for (const key of Object.keys(rules)) {
      if (key === 'base') continue;

      const pairs = key.split('+');
      for (const pair of pairs) {
        const colonIdx = pair.indexOf(':');
        if (colonIdx === -1) continue;
        const prop = pair.slice(0, colonIdx);
        const value = pair.slice(colonIdx + 1);

        // Skip known built-in values
        const knownForProp = knownForComponent[prop];
        if (knownForProp && knownForProp.includes(value)) continue;

        if (!customValues[component]) customValues[component] = {};
        if (!customValues[component][prop]) customValues[component][prop] = new Set();
        customValues[component][prop].add(value);
      }
    }
  }

  // Check if we found any custom values
  const hasCustom = Object.values(customValues).some(
    props => Object.values(props).some(values => values.size > 0)
  );
  if (!hasCustom) return null;

  const sections = ['// Generated by xds theme build', 'export {};', ''];

  for (const [component, props] of Object.entries(customValues)) {
    for (const [prop, values] of Object.entries(props)) {
      if (values.size === 0) continue;

      const pascal = toPascalCase(component);
      const propPascal = prop.charAt(0).toUpperCase() + prop.slice(1);
      const modulePath = `@xds/core/${pascal}`;
      const interfaceName = `XDS${pascal}${propPascal}Map`;

      sections.push(`declare module '${modulePath}' {`);
      sections.push(`  interface ${interfaceName} {`);
      for (const v of values) {
        sections.push(`    '${v}': true;`);
      }
      sections.push('  }');
      sections.push('}');
      sections.push('');
    }
  }

  return sections.join('\n');
}

/**
 * Resolve a token value — [light, dark] tuple becomes light-dark()
 */
function resolveTokenValue(value) {
  if (Array.isArray(value)) {
    return `light-dark(${value[0]}, ${value[1]})`;
  }
  return value;
}

/**
 * Parse a component style key into a CSS selector suffix.
 * - `base` → ''
 * - `variant:secondary` → '.secondary'
 * - `level:1` → '.level-1' (digits get prefixed)
 * - `variant:destructive+size:sm` → '.destructive.sm'
 *
 * <!-- SYNC: packages/core/src/utils/parseStyleKey.ts -->
 * <!-- SYNC: packages/core/src/utils/xdsClassName.ts -->
 * The digit-prefix and value-to-class logic must match across all three files.
 */

// =============================================================================
// Container padding mapping
// =============================================================================

const CONTAINER_COMPONENTS = new Set(['card', 'section', 'dialog']);
const PADDING_PROPS = new Set([
  'padding', 'paddingBlock', 'paddingInline',
  'paddingBlockStart', 'paddingBlockEnd',
  'paddingInlineStart', 'paddingInlineEnd',
]);

function parsePadding(props) {
  const result = {};
  for (const [prop, value] of props) {
    switch (prop) {
      case 'padding': {
        const parts = value.trim().split(/\s+/);
        if (parts.length === 1) {
          result.blockStart = parts[0];
          result.blockEnd = parts[0];
          result.inline = parts[0];
        } else if (parts.length === 2) {
          result.blockStart = parts[0];
          result.blockEnd = parts[0];
          result.inline = parts[1];
        } else if (parts.length >= 3) {
          result.blockStart = parts[0];
          result.inline = parts[1];
          result.blockEnd = parts[2];
        }
        break;
      }
      case 'paddingBlock': {
        const parts = value.trim().split(/\s+/);
        result.blockStart = parts[0];
        result.blockEnd = parts[1] ?? parts[0];
        break;
      }
      case 'paddingInline': {
        const parts = value.trim().split(/\s+/);
        if (parts.length === 1) {
          result.inline = parts[0];
        } else {
          result.inlineStart = parts[0];
          result.inlineEnd = parts[1];
        }
        break;
      }
      case 'paddingBlockStart':
        result.blockStart = value;
        break;
      case 'paddingBlockEnd':
        result.blockEnd = value;
        break;
      case 'paddingInlineStart':
        result.inlineStart = value;
        break;
      case 'paddingInlineEnd':
        result.inlineEnd = value;
        break;
    }
  }
  return result;
}

function expandContainerPadding(component, parsed) {
  const prefix = `--xds-${component}-padding`;
  const tokens = [];

  // Resolve effective inline values (inlineStart/End override inline)
  const effectiveInlineStart = parsed.inlineStart ?? parsed.inline;
  const effectiveInlineEnd = parsed.inlineEnd ?? parsed.inline;
  const inlineSymmetric =
    effectiveInlineStart != null &&
    effectiveInlineEnd != null &&
    effectiveInlineStart === effectiveInlineEnd;

  // If all sides are the same, emit the shorthand token only
  const allSame =
    inlineSymmetric &&
    parsed.blockStart != null &&
    parsed.blockEnd != null &&
    effectiveInlineStart === parsed.blockStart &&
    parsed.blockStart === parsed.blockEnd;

  if (allSame) {
    tokens.push([prefix, effectiveInlineStart]);
    return tokens;
  }

  // Directional tokens
  if (parsed.inlineStart != null || parsed.inlineEnd != null) {
    // Asymmetric inline — emit start and end separately
    if (effectiveInlineStart != null) {
      tokens.push([`${prefix}-inline-start`, effectiveInlineStart]);
    }
    if (effectiveInlineEnd != null) {
      tokens.push([`${prefix}-inline-end`, effectiveInlineEnd]);
    }
  } else if (parsed.inline != null) {
    tokens.push([`${prefix}-inline`, parsed.inline]);
  }
  if (parsed.blockStart != null) {
    tokens.push([`${prefix}-block-start`, parsed.blockStart]);
  }
  if (parsed.blockEnd != null) {
    tokens.push([`${prefix}-block-end`, parsed.blockEnd]);
  }
  return tokens;
}

function parseStyleKey(key) {
  if (key === 'base') return '';
  return key
    .split('+')
    .map(part => {
      const [prop, value] = part.split(':');
      // Bare state name (no colon) — e.g. 'checked', 'disabled', 'selected'
      if (value === undefined) {
        return `.${prop}`;
      }
      if (/^\d/.test(value)) {
        return `.${prop}-${value}`;
      }
      return `.${value}`;
    })
    .join('');
}

/**
 * Maps component style keys to HTML elements for prose co-selection.
 *
 * When a theme overrides a prose-related component, the HTML element
 * counterpart should get the same styles. This map defines which
 * HTML elements correspond to which component + style key.
 *
 * 'base' overrides apply to all HTML counterparts.
 * Variant-specific overrides only apply to matching elements.
 */
const PROSE_COMPONENT_MAP = {
  heading: {
    base: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
  },
  text: {
    base: ['p', 'small'],
    'type:code': ['code', 'pre'],
    'type:supporting': ['small'],
  },
  kbd: {
    base: ['kbd'],
  },
  link: {
    base: ['a'],
  },
  divider: {
    base: ['hr'],
  },
};

/**
 * Generate CSS from a theme definition object.
 *
 * When prose is enabled, component overrides for prose-related components
 * (heading, text, kbd, link, divider) co-select their HTML element
 * counterparts so raw markup inherits the theme's component styling.
 */
function generateCSS(themeDef, {prose = true} = {}) {
  const parts = [];
  const scopeSelector = `[data-xds-theme="${themeDef.name}"]`;

  // Token overrides — applied to the scope root
  if (themeDef.tokens && Object.keys(themeDef.tokens).length > 0) {
    const declarations = Object.entries(themeDef.tokens)
      .map(([prop, value]) => `    ${prop}: ${resolveTokenValue(value)};`)
      .join('\n');
    parts.push(`  :scope {\n${declarations}\n  }`);
  }

  // Component overrides
  if (themeDef.components) {
    for (const [component, rules] of Object.entries(themeDef.components)) {
      for (const [key, styles] of Object.entries(rules)) {
        const entries = Object.entries(styles);
        if (entries.length > 0) {
          const suffix = parseStyleKey(key);

          // Separate regular properties from pseudo-class overrides
          const props = [];
          const pseudos = [];

          for (const [prop, value] of entries) {
            if (prop.startsWith(':') && typeof value === 'object') {
              pseudos.push([prop, value]);
            } else {
              props.push([prop, value]);
            }
          }

          // Build selector — co-select HTML elements for prose-related components
          const xdsSelector = `.xds-${component}${suffix}`;
          let baseSelector = `  ${xdsSelector}`;

          if (prose) {
            const htmlElements = PROSE_COMPONENT_MAP[component]?.[key];
            if (htmlElements) {
              const htmlSelector = htmlElements.map(el => `  ${el}`).join(',\n');
              baseSelector = `  ${xdsSelector},\n${htmlSelector}`;
            }
          }

          // Container padding mapping
          let finalProps = props;
          if (CONTAINER_COMPONENTS.has(component)) {
            const paddingProps = props.filter(([p]) => PADDING_PROPS.has(p));
            if (paddingProps.length > 0) {
              const nonPaddingProps = props.filter(([p]) => !PADDING_PROPS.has(p));
              const parsed = parsePadding(paddingProps);
              const containerTokens = expandContainerPadding(component, parsed);
              finalProps = [...nonPaddingProps, ...containerTokens];
            }
          }

          // Emit base rule
          if (finalProps.length > 0) {
            const declarations = finalProps
              .map(([prop, value]) => `    ${toKebabCase(prop)}: ${value};`)
              .join('\n');
            parts.push(`${baseSelector} {\n${declarations}\n  }`);
          }

          // Emit pseudo-class rules
          for (const [pseudo, pseudoStyles] of pseudos) {
            const pseudoEntries = Object.entries(pseudoStyles);
            if (pseudoEntries.length > 0) {
              const declarations = pseudoEntries
                .map(([prop, value]) => `    ${toKebabCase(prop)}: ${value};`)
                .join('\n');
              // Pseudo-class rules only on xds selector, not prose co-selection
              parts.push(
                `  ${xdsSelector}${pseudo} {\n${declarations}\n  }`,
              );
            }
          }
        }
      }
    }
  }

  if (parts.length === 0) return '';

  const inner = parts.join('\n\n');
  return `@scope (${scopeSelector}) to ([data-xds-theme]) {\n${inner}\n}`;
}

// =============================================================================
// Prose CSS generation
// =============================================================================

/**
 * Prose HTML element → XDS component class mappings.
 *
 * Prose maps raw HTML elements to their XDS component counterparts so that
 * plain markup (e.g. rendered markdown) inherits the component styles from
 * xds.base. The theme doesn't redefine the styles — it just aliases the
 * selectors, scoped under the theme boundary.
 */
const PROSE_MAPPINGS = [
  // Headings
  {html: 'h1', xds: '.xds-heading.level-1'},
  {html: 'h2', xds: '.xds-heading.level-2'},
  {html: 'h3', xds: '.xds-heading.level-3'},
  {html: 'h4', xds: '.xds-heading.level-4'},
  {html: 'h5', xds: '.xds-heading.level-5'},
  {html: 'h6', xds: '.xds-heading.level-6'},
  // Text
  {html: 'p', xds: '.xds-text.body'},
  {html: 'small', xds: '.xds-text.supporting'},
  {html: 'code', xds: '.xds-text.code'},
  {html: 'pre', xds: '.xds-text.code'},
  // Standalone components
  {html: 'kbd', xds: '.xds-kbd'},
  {html: 'a', xds: '.xds-link'},
  {html: 'hr', xds: '.xds-divider'},
];

/**
 * Generate prose CSS — aliases raw HTML elements to XDS component classes.
 *
 * The actual styles live in xds.base (component CSS). Prose just says
 * "inside this theme, an <h1> should look like .xds-heading.level-1".
 * This is done via CSS @extend-like pattern: each HTML element inherits
 * the same class as its XDS counterpart.
 */
function generateProseCSS(themeDef) {
  const scopeSelector = `[data-xds-theme="${themeDef.name}"]`;

  // Each mapping becomes: h1 { /* same styles as .xds-heading.level-1 */ }
  // Since we can't @extend in plain CSS, we use the component's CSS custom
  // properties which are already set by xds.base. The prose elements just
  // need the same structural styles (font-family, margin reset, etc.)
  // that the base heading/text components apply.
  //
  // For now, we co-select: the component overrides in generateCSS already
  // target .xds-button, .xds-card, etc. Prose adds the HTML element as
  // an additional selector for component overrides that have an HTML equivalent.
  const rules = PROSE_MAPPINGS.map(
    ({html, xds}) => `  ${html} { @extend ${xds}; }`,
  );

  // CSS @extend isn't widely supported yet. Instead, generate rules that
  // reference the same token-based custom properties the components use.
  // This is a thin layer — just structural resets + token references.
  const parts = [];

  // Heading resets — all heading elements get the base heading treatment
  parts.push(`  :is(h1, h2, h3, h4, h5, h6) {\n    font-family: var(--font-family-heading);\n    font-weight: var(--font-weight-semibold);\n    color: var(--color-text-primary);\n    margin: 0;\n  }`);

  // Per-level heading sizes
  const headingSizes = {
    h1: {fontSize: 'var(--font-size-2xl)', lineHeight: '1.2'},
    h2: {fontSize: 'var(--font-size-xl)', lineHeight: '1.333'},
    h3: {fontSize: 'var(--font-size-lg)', lineHeight: '1.25'},
    h4: {fontSize: 'var(--font-size-base)', lineHeight: 'var(--leading-base)'},
    h5: {fontSize: 'var(--font-size-base)', lineHeight: 'var(--leading-base)'},
    h6: {fontSize: 'var(--font-size-xs)', lineHeight: '1.333'},
  };

  for (const [el, styles] of Object.entries(headingSizes)) {
    const declarations = Object.entries(styles)
      .map(([prop, value]) => `    ${toKebabCase(prop)}: ${value};`)
      .join('\n');
    parts.push(`  ${el} {\n${declarations}\n  }`);
  }

  // Text element resets
  parts.push(`  p {\n    font-family: var(--font-family-heading);\n    color: var(--color-text-primary);\n    margin: 0;\n    font-size: var(--font-size-base);\n    line-height: var(--leading-base);\n  }`);

  parts.push(`  small {\n    font-size: var(--font-size-xs);\n    line-height: 1.333;\n    color: var(--color-text-secondary);\n  }`);

  parts.push(`  code, pre {\n    font-family: var(--font-family-code);\n    font-size: var(--font-size-base);\n    line-height: var(--leading-base);\n  }`);

  parts.push(`  hr {\n    border: none;\n    border-top: 1px solid var(--color-border);\n    margin: 0;\n  }`);

  const inner = parts.join('\n\n');
  return `@scope (${scopeSelector}) to ([data-xds-theme]) {\n${inner}\n}`;
}

/**
 * Import a theme module using jiti and find the defineTheme() result.
 * Returns the resolved XDSDefinedTheme object.
 */
async function importThemeModule(filePath) {
  const jiti = createJiti(import.meta.url, {
    moduleCache: false,
    jsx: true,
  });

  const mod = await jiti.import(filePath, {default: true});

  if (isThemeObject(mod)) return mod;

  if (mod && typeof mod === 'object') {
    for (const value of Object.values(mod)) {
      if (isThemeObject(value)) return value;
    }
  }

  throw new Error(
    `Could not find a defineTheme() result in ${filePath}.\n` +
    `Expected an export like: export const myTheme = defineTheme({ name: '...', tokens: {...} })`,
  );
}

function isThemeObject(value) {
  return (
    value &&
    typeof value === 'object' &&
    typeof value.name === 'string' &&
    value.tokens &&
    typeof value.tokens === 'object'
  );
}

/**
 * Extract the theme definition from a JS/TS file.
 * Tries jiti first (full TS support), falls back to regex+eval.
 */
async function extractThemeDefinition(filePath) {
  try {
    return await importThemeModule(filePath);
  } catch (jitiError) {
    try {
      return extractThemeDefinitionLegacy(filePath);
    } catch {
      throw new Error(
        `Failed to load theme from ${filePath}: ${jitiError.message}\n` +
        `Make sure all imports in the theme file are resolvable.`,
      );
    }
  }
}

/**
 * Fallback extraction via regex + eval.
 * Only works for plain object literals — can't follow imports or variables.
 */
function extractThemeDefinitionLegacy(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');

  const defineMatch = content.match(/defineTheme\s*\(\s*({[\s\S]*?})\s*\)/);
  if (!defineMatch) {
    const defaultMatch = content.match(/export\s+default\s+({[\s\S]*?});/);
    if (!defaultMatch) {
      throw new Error(
        `Could not find defineTheme() call or default export in ${filePath}.\n` +
        `Expected: defineTheme({ name: '...', tokens: {...} })`,
      );
    }
    // eslint-disable-next-line no-eval
    return eval(`(${defaultMatch[1]})`);
  }

  let objStr = defineMatch[1];
  objStr = objStr.replace(/\s+as\s+const/g, '');
  objStr = objStr.replace(/icons:\s*[a-zA-Z_][a-zA-Z0-9_]*/g, 'icons: undefined');

  try {
    // eslint-disable-next-line no-eval
    return eval(`(${objStr})`);
  } catch (e) {
    throw new Error(
      `Failed to parse theme definition in ${filePath}: ${e.message}\n` +
      `Make sure the defineTheme() argument is a plain object literal.`,
    );
  }
}

/**
 * Extract icon import info from a theme source file.
 * Returns { importPath, exportName } or null if no icons.
 *
 * Looks for patterns like:
 *   import { defaultIconRegistry } from './icons';
 *   icons: defaultIconRegistry,
 */
function extractIconInfo(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');

  // Find the icons field in defineTheme
  const iconsMatch = content.match(/icons:\s*([a-zA-Z_][a-zA-Z0-9_]*)/);
  if (!iconsMatch) return null;

  const varName = iconsMatch[1];

  // Find the import for that variable
  const importRegex = new RegExp(
    `import\\s*{[^}]*\\b${varName}\\b[^}]*}\\s*from\\s*['"]([^'"]+)['"]`,
  );
  const importMatch = content.match(importRegex);
  if (!importMatch) return null;

  return {
    exportName: varName,
    importPath: importMatch[1],
  };
}

/**
 * Generate a minimal JS module for a built theme.
 * Includes the theme name, marker, and re-exports the icon registry.
 * All styling is in the CSS file.
 */
function generateBuiltModule(themeDef, iconInfo) {
  const iconImport = iconInfo
    ? `import { ${iconInfo.exportName} } from '${iconInfo.importPath}';\n`
    : '';
  const iconsField = iconInfo ? `  icons: ${iconInfo.exportName},` : '';
  const iconReExport = iconInfo
    ? `\nexport { ${iconInfo.exportName} };\n`
    : '';

  // Resolve token values — tuples become light-dark() strings
  const resolvedTokens = {};
  if (themeDef.tokens) {
    for (const [key, value] of Object.entries(themeDef.tokens)) {
      resolvedTokens[key] = resolveTokenValue(value);
    }
  }

  const tokensStr = JSON.stringify(resolvedTokens, null, 2)
    .split('\n')
    .map((line, i) => (i === 0 ? line : '  ' + line))
    .join('\n');

  return `${iconImport}/**
 * ${themeDef.name} theme — built by \`${getRunPrefix()} xds theme build\`
 * Import the CSS file alongside this module:
 *
 *   import { ${toIdentifier(themeDef.name)}Theme } from './${themeDef.name}';
 *   import './${themeDef.name}.css';
 */
export const ${toIdentifier(themeDef.name)}Theme = {
  name: '${themeDef.name}',
  __built: true,
  tokens: ${tokensStr},
${iconsField}
};
${iconReExport}`;
}

/**
 * Generate TypeScript declarations for a built theme module.
 */
function generateBuiltTypes(themeDef, iconInfo) {
  const iconType = iconInfo
    ? `import type { XDSIconRegistry } from '@xds/core/Icon';
export declare const ${iconInfo.exportName}: XDSIconRegistry;
`
    : '';
  return `import type { XDSDefinedTheme } from '@xds/core/theme';
${iconType}export declare const ${toIdentifier(themeDef.name)}Theme: XDSDefinedTheme;
`;
}

// =============================================================================
// Component validation
// =============================================================================

/**
 * Known XDS component names and their visual props.
 * Used to warn on typos in defineTheme component overrides.
 */
const KNOWN_COMPONENTS = {
  appshell: ['position'],
  aspectratio: [],
  avatar: ['size'],
  badge: ['variant', 'color'],
  banner: ['container', 'status'],
  breadcrumbs: ['variant'],
  button: ['variant', 'size'],
  calendar: [],
  card: [],
  center: [],
  checkboxinput: [],
  collapsible: [],
  dateinput: [],
  dialog: ['variant', 'position'],
  divider: ['variant', 'orientation'],
  dropdownmenu: [],
  emptystate: [],
  field: [],
  formlayout: [],
  grid: ['align'],
  heading: ['level'],
  icon: ['size', 'color'],
  kbd: [],
  layer: [],
  layout: [],
  link: ['color'],
  list: ['type', 'density'],
  mobilenav: [],
  moremenu: [],
  navicon: [],
  numberinput: [],
  pagination: ['variant'],
  progressbar: ['variant', 'size'],
  radiolist: ['orientation'],
  section: ['variant'],
  selector: ['type', 'size', 'color'],
  sidenav: [],
  skeleton: [],
  slider: ['orientation'],
  spinner: ['size'],
  stack: [],
  statusdot: ['variant', 'size'],
  switch: [],
  table: [],
  tablist: ['type'],
  text: ['type', 'color'],
  textarea: [],
  textinput: [],
  timeinput: [],
  token: ['color'],
  tokenizer: [],
  topnav: [],
  typeahead: ['type', 'size', 'color'],
};

/**
 * Validate component overrides in a theme definition.
 * Warns on unknown component names and unknown prop names.
 * Returns array of warning strings.
 */
function validateComponentOverrides(themeDef) {
  const warnings = [];
  if (!themeDef.components) return warnings;

  for (const [component, rules] of Object.entries(themeDef.components)) {
    // Check component name
    if (!(component in KNOWN_COMPONENTS)) {
      const similar = Object.keys(KNOWN_COMPONENTS)
        .filter((k) => {
          if (k.includes(component) || component.includes(k)) return true;
          // Levenshtein distance 1-2 for short names
          if (Math.abs(k.length - component.length) <= 2) {
            let diff = 0;
            const longer = k.length >= component.length ? k : component;
            const shorter = k.length < component.length ? k : component;
            let j = 0;
            for (let i = 0; i < longer.length && diff <= 2; i++) {
              if (longer[i] !== shorter[j]) diff++;
              else j++;
            }
            diff += shorter.length - j;
            return diff <= 2;
          }
          return false;
        })
        .slice(0, 3);
      const hint = similar.length > 0 ? ` Did you mean: ${similar.join(', ')}?` : '';
      warnings.push(`Unknown component "${component}".${hint}`);
      continue;
    }

    // Check prop names in prop:value keys
    const knownProps = KNOWN_COMPONENTS[component];
    for (const key of Object.keys(rules)) {
      if (key === 'base') continue;

      // Parse prop:value pairs (e.g. 'variant:secondary' or 'variant:destructive+size:sm')
      const pairs = key.split('+');
      for (const pair of pairs) {
        const [prop] = pair.split(':');
        if (prop && !knownProps.includes(prop)) {
          const hint =
            knownProps.length > 0
              ? ` Known props: ${knownProps.join(', ')}`
              : ' This component has no variant props.';
          warnings.push(
            `Unknown prop "${prop}" on component "${component}".${hint}`,
          );
        }
      }
    }
  }

  return warnings;
}

/**
 * Validate that themes don't set private (--_*) CSS custom properties directly.
 * Private vars are internal implementation details managed by the derived var
 * expansion pipeline. Theme authors should write standard CSS properties
 * (e.g. borderRadius, padding) instead.
 *
 * Returns array of error strings.
 */
function validatePrivateVars(themeDef) {
  const errors = [];
  if (!themeDef.components) return errors;

  for (const [component, rules] of Object.entries(themeDef.components)) {
    for (const [key, styles] of Object.entries(rules)) {
      for (const [prop, value] of Object.entries(styles)) {
        if (typeof prop === 'string' && prop.startsWith('--_')) {
          errors.push(
            `Component "${component}" (${key}) sets private var "${prop}". ` +
            `Private vars (--_*) are internal — use standard CSS properties ` +
            `(e.g. borderRadius, padding) instead. The pipeline expands them automatically.`,
          );
        }
      }
    }
  }

  return errors;
}

export function registerTheme(program) {
  const theme = program
    .command('theme')
    .description('Theme tools — build, export, and manage themes')
    .action((options, cmd) => {
      // Parent group has no default behaviour. If the user passed an
      // unknown subcommand (e.g. `xds theme bogus`), Commander hands it to
      // us as a positional in cmd.args — exit 1 with a clear error.
      const extras = (cmd && cmd.args) || [];
      if (extras.length > 0) {
        const unknown = String(extras[0]);
        const known = (theme.commands || []).map((c) => c.name());
        const suggestions = known.map((name) => ({name, reason: 'available subcommand'}));
        cliError(`unknown subcommand 'theme ${unknown}'`, {suggestions});
        return;
      }
      // Bare `xds theme` — show the subcommand list. Exit 0 (help is success).
      theme.help();
    });

  theme
    .command('build <file>')
    .description('Compile a defineTheme file to CSS + JS')
    .option('-o, --out <path>', 'Output CSS file path')
    .option('--no-prose', 'Skip prose mappings (h1, p, code, hr, etc.)')
    .action(async (file, options) => {
      const filePath = path.resolve(process.cwd(), file);
      const json = program.opts().json || false;

      if (!fs.existsSync(filePath)) {
        cliError(`File not found: ${filePath}`);
        return;
      }

      if (!json) humanLog(`\nBuilding theme from ${path.relative(process.cwd(), filePath)}...`);

      // Extract theme definition
      let themeDef;
      try {
        themeDef = await extractThemeDefinition(filePath);
      } catch (e) {
        cliError(e.message);
        return;
      }

      if (!themeDef.name) {
        cliError('Theme must have a name property.');
        return;
      }

      // Path-safety: the theme name is used to derive output filenames
      // (e.g. `${name}.css`, `${name}.js`). Reject names containing path
      // separators or traversal markers — `../../escaped` would otherwise
      // write JS modules outside the input directory.
      try {
        sanitizeName(themeDef.name, {label: 'theme name'});
      } catch (err) {
        if (err instanceof PathSafetyError) {
          cliError(err.message);
          return;
        }
        throw err;
      }

      // Validate component overrides
      const warnings = validateComponentOverrides(themeDef);
      const warningMessages = [];
      for (const w of warnings) {
        warningMessages.push(w);
        if (!json) console.warn(`  ⚠ ${w}`);
      }

      // Validate no private vars are set directly
      const privateVarErrors = validatePrivateVars(themeDef);
      for (const e of privateVarErrors) {
        warningMessages.push(e);
        if (!json) console.error(`  ✗ ${e}`);
      }
      if (privateVarErrors.length > 0 && !json) {
        console.error(`\n  ${privateVarErrors.length} private var error(s). Use standard CSS properties instead.`);
      }

      // Generate CSS using the shared generateThemeRules from core.
      // This ensures build and runtime produce identical rule sets.
      let css;
      let resolvedTheme;
      if (_defineTheme && _generateThemeRules) {
        // jiti returns an already-resolved theme; legacy eval returns raw input.
        const isAlreadyResolved = !themeDef.typography && !themeDef.motion && !themeDef.radius;
        if (isAlreadyResolved) {
          resolvedTheme = themeDef;
        } else {
          resolvedTheme = _defineTheme({
            name: themeDef.name,
            typography: themeDef.typography,
            motion: themeDef.motion,
            radius: themeDef.radius,
            tokens: themeDef.tokens,
            components: themeDef.components,
          });
        }
        const scopeSelector = `[data-xds-theme="${themeDef.name}"]`;
        const scopeTo = `[data-xds-theme]`;

        if (_generateThemeRulesSplit) {
          const {component, prose} = _generateThemeRulesSplit(resolvedTheme);
          const cssParts = [];
          if (options.prose !== false && prose.length > 0) {
            const proseInner = prose.join('\n\n');
            cssParts.push(`@layer reset {\n@scope (${scopeSelector}) to (${scopeTo}) {\n${proseInner}\n}\n}`);
          }
          if (component.length > 0) {
            const componentInner = component.join('\n\n');
            const componentScope = `@scope (${scopeSelector}) to (${scopeTo}) {\n${componentInner}\n}`;
            const colorSchemeDecl = componentScope.includes('light-dark(')
              ? '  :root { color-scheme: light dark; }\n\n'
              : '';
            cssParts.push(`@layer xds-theme {\n${colorSchemeDecl}${componentScope}\n}`);
          }
          // On-media rules (XDSMediaTheme dark/light surface overrides)
          if (_generateOnMediaCSS) {
            const onMediaCss = _generateOnMediaCSS(resolvedTheme);
            if (onMediaCss) {
              cssParts.push(`@layer xds-theme {\n${onMediaCss}\n}`);
            }
          }
          css = cssParts.join('\n\n') + '\n';
        } else {
          const rules = _generateThemeRules(resolvedTheme);
          if (rules.length > 0) {
            const inner = rules.join('\n\n');
            const scopeBlock = `@scope (${scopeSelector}) to (${scopeTo}) {\n${inner}\n}`;
            const colorSchemeDecl = scopeBlock.includes('light-dark(')
              ? '  :root { color-scheme: light dark; }\n\n'
              : '';
            css = `@layer xds-theme {\n${colorSchemeDecl}${scopeBlock}\n}\n`;
            // On-media rules (legacy path)
            if (_generateOnMediaCSS) {
              const onMediaCss = _generateOnMediaCSS(resolvedTheme);
              if (onMediaCss) {
                css += `\n@layer xds-theme {\n${onMediaCss}\n}\n`;
              }
            }
          }
        }
      } else {
        // Legacy fallback when core isn't built yet
        const scopeBlocks = [];
        if (options.prose !== false) {
          const proseCss = generateProseCSS(themeDef);
          if (proseCss) scopeBlocks.push(proseCss);
        }
        const mainCss = generateCSS(themeDef);
        if (mainCss) scopeBlocks.push(mainCss);
        if (scopeBlocks.length === 0) {
          if (!json) humanLog('No overrides found — nothing to build.');
          return;
        }
        const joined = scopeBlocks.join('\n\n');
        const colorSchemeDecl = joined.includes('light-dark(')
          ? '  :root { color-scheme: light dark; }\n\n'
          : '';
        css = `@layer xds-theme {\n${colorSchemeDecl}${joined}\n}\n`;
      }

      // Source path relative to cwd — used in @generated headers
      const sourceRelative = path.relative(process.cwd(), filePath);
      const buildCommand = `xds theme build ${sourceRelative}${options.out ? ' --out ' + path.relative(process.cwd(), path.resolve(process.cwd(), options.out)) : ''}`;

      // Determine output path
      const outPath = options.out
        ? path.resolve(process.cwd(), options.out)
        : filePath.replace(/\.(ts|tsx|js|jsx|mjs)$/, '.css');

      const displayTheme = resolvedTheme || themeDef;
      const tokenCount = displayTheme.tokens ? Object.keys(displayTheme.tokens).length : 0;
      const componentCount = displayTheme.components ? Object.keys(displayTheme.components).length : 0;
      const size = (Buffer.byteLength(css) / 1024).toFixed(1);

      // Compute all output paths up front so we can validate them as a
      // group BEFORE writing anything. Previously the CSS would be written
      // first; if the JS write failed (e.g. ENOENT, permission), the CSS
      // was left as orphaned half-built output. Stage-then-commit avoids
      // that.
      const outDir = path.dirname(outPath);
      const baseName = themeDef.name;
      const jsPath = path.join(outDir, `${baseName}.js`);
      const dtsPath = path.join(outDir, `${baseName}.d.ts`);

      const iconInfo = extractIconInfo(filePath);

      // Generate all file contents in memory first.
      const cssContent = generatedHeader(sourceRelative, 'css', buildCommand) + css;
      const jsContent = generatedHeader(sourceRelative, 'js', buildCommand) + generateBuiltModule(resolvedTheme || themeDef, iconInfo);
      const dtsContent = generatedHeader(sourceRelative, 'ts', buildCommand) + generateBuiltTypes(themeDef, iconInfo);

      // Type augmentation .d.ts if theme has custom prop values
      const augmentationSource = resolvedTheme || themeDef;
      const variantDecl = await generateVariantDeclarationsAsync(augmentationSource);
      const variantDtsPath = variantDecl ? path.join(outDir, `${baseName}.variants.d.ts`) : null;
      const variantContent = variantDecl
        ? generatedHeader(sourceRelative, 'ts', buildCommand) + variantDecl
        : null;

      // Atomic-ish write: stage every file as `<dest>.tmp`, then rename
      // each into place. If any stage step fails we clean up partials and
      // exit; if a rename fails mid-way we still have the originals (or
      // nothing) — never a half-built output set.
      const writes = [
        {dest: outPath, content: cssContent},
        {dest: jsPath, content: jsContent},
        {dest: dtsPath, content: dtsContent},
      ];
      if (variantDtsPath) {
        writes.push({dest: variantDtsPath, content: variantContent});
      }

      fs.mkdirSync(outDir, {recursive: true});
      const staged = [];
      try {
        for (const w of writes) {
          const tmp = `${w.dest}.${process.pid}.tmp`;
          fs.writeFileSync(tmp, w.content);
          staged.push({tmp, dest: w.dest});
        }
        for (const s of staged) {
          fs.renameSync(s.tmp, s.dest);
        }
      } catch (err) {
        // Roll back any temp files we managed to create.
        for (const s of staged) {
          try { fs.rmSync(s.tmp, {force: true}); } catch { /* best-effort */ }
        }
        const msg = `Failed to write theme outputs: ${err.message}`;
        cliError(msg);
        return;
      }

      if (!json) {
        humanLog(`\n✓ ${path.relative(process.cwd(), outPath)}`);
        humanLog(`  ${tokenCount} token overrides, ${componentCount} component overrides`);
        humanLog(`  ${size} KB`);
        humanLog(`✓ ${path.relative(process.cwd(), jsPath)}`);
        humanLog(`✓ ${path.relative(process.cwd(), dtsPath)}`);
        if (variantDtsPath) {
          const augCount = (variantDecl.match(/': true;/g) || []).length;
          humanLog(`✓ ${path.relative(process.cwd(), variantDtsPath)} (${augCount} type augmentations)`);
        }
      }

      if (json) {
        return jsonOut('theme.build', {
          name: themeDef.name,
          tokenCount,
          componentCount,
          sizeKB: parseFloat(size),
          outputs: {
            css: path.relative(process.cwd(), outPath),
            js: path.relative(process.cwd(), jsPath),
            dts: path.relative(process.cwd(), dtsPath),
            ...(variantDecl ? {variantsDts: path.relative(process.cwd(), variantDtsPath)} : {}),
          },
          warnings: warningMessages,
        });
      }

      // Print install instructions
      const relDir = path.relative(process.cwd(), outDir);
      const exportName = `${toIdentifier(baseName)}Theme`;
      humanLog(`
Install in your app:

  import { ${exportName} } from './${relDir}/${baseName}';
  import './${relDir}/${baseName}.css';

  <XDSTheme theme={${exportName}}>
    <App />
  </XDSTheme>

Or with a <link> tag:

  import { ${exportName} } from './${relDir}/${baseName}';

  <link rel="stylesheet" href="./${relDir}/${baseName}.css" />
  <XDSTheme theme={${exportName}}>
    <App />
  </XDSTheme>
`);

      // Print font declaration warnings (derived from typography roles)
      if (resolvedTheme && resolvedTheme.fonts && resolvedTheme.fonts.length > 0) {
        humanLog(`\n⚠ Theme "${themeDef.name}" requires fonts not included in the build:`);
        for (const font of resolvedTheme.fonts) {
          humanLog(`  ${font.family} — add to your document <head>:`);
          humanLog(`  <link rel="stylesheet" href="${font.url}" />`);
        }
        humanLog('');
      }
    });
}
