#!/usr/bin/env node
/**
 * @file Build pipeline: eval → data injection → Vite build → static HTML
 *
 * Orchestrates the full report generation pipeline.
 *
 * Usage:
 *   tsx src/build-report.ts --iteration <id>
 *   tsx src/build-report.ts --iteration <id> --baseline <id>
 *   tsx src/build-report.ts --iteration <id> --baseline <id> --with-screenshots
 *   tsx src/build-report.ts --iteration <id> --dev
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import {execSync} from 'node:child_process';
import {getResultsDir, readJson, writeJson, ensureDir} from './utils.js';
import type {UniversalAggregate, UniversalComparison} from './types.js';

const APP_DIR = path.join(import.meta.dirname, '..', 'app');

function parseArgs(): {
  iteration: string;
  baseline?: string;
  withScreenshots: boolean;
  dev: boolean;
} {
  const args = process.argv.slice(2);
  let iteration = '';
  let baseline: string | undefined;
  let withScreenshots = false;
  let dev = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--iteration' && args[i + 1]) {
      iteration = args[i + 1];
      i++;
    } else if (args[i] === '--baseline' && args[i + 1]) {
      baseline = args[i + 1];
      i++;
    } else if (args[i] === '--with-screenshots') {
      withScreenshots = true;
    } else if (args[i] === '--dev') {
      dev = true;
    }
  }

  if (!iteration) {
    console.error(
      'Usage: tsx src/build-report.ts --iteration <id> [--baseline <id>] [--with-screenshots] [--dev]',
    );
    process.exit(1);
  }

  return {iteration, baseline, withScreenshots, dev};
}

function ensureUniversalJson(iteration: string): UniversalAggregate {
  const resultsDir = getResultsDir();
  const universalPath = path.join(resultsDir, iteration, 'universal.json');

  if (!fs.existsSync(universalPath)) {
    console.log(`Generating universal.json for ${iteration}...`);
    execSync(
      `tsx ${path.join(import.meta.dirname, 'universal-aggregate.ts')} --iteration ${iteration}`,
      {cwd: path.join(import.meta.dirname, '..'), stdio: 'inherit'},
    );
  }

  return readJson<UniversalAggregate>(universalPath);
}

function ensureComparison(
  xdsId: string,
  baselineId: string,
): UniversalComparison {
  const resultsDir = getResultsDir();
  const comparisonPath = path.join(
    resultsDir,
    `comparison-${xdsId}-${baselineId}.json`,
  );

  if (!fs.existsSync(comparisonPath)) {
    console.log(`Generating comparison for ${xdsId} vs ${baselineId}...`);
    execSync(
      `tsx ${path.join(import.meta.dirname, 'universal-compare.ts')} --xds ${xdsId} --baseline ${baselineId}`,
      {cwd: path.join(import.meta.dirname, '..'), stdio: 'inherit'},
    );
  }

  return readJson<UniversalComparison>(comparisonPath);
}

function generateReportData(opts: {
  iteration: string;
  iterationData: UniversalAggregate;
  baseline?: string;
  comparison?: UniversalComparison;
  manifest: unknown;
  screenshotPaths?: string[];
}): string {
  const lines: string[] = [
    '// AUTO-GENERATED — do not edit',
    '// Generated by build-report.ts',
    '',
    `export const iterationId = ${JSON.stringify(opts.iteration)};`,
    '',
    `export const iterationData = ${JSON.stringify(opts.iterationData, null, 2)} as const;`,
    '',
    `export const manifest = ${JSON.stringify(opts.manifest, null, 2)} as const;`,
    '',
  ];

  if (opts.baseline && opts.comparison) {
    lines.push(`export const baselineId = ${JSON.stringify(opts.baseline)};`);
    lines.push('');
    lines.push(
      `export const comparison = ${JSON.stringify(opts.comparison, null, 2)} as const;`,
    );
    lines.push('');
  } else {
    lines.push('export const baselineId: string | undefined = undefined;');
    lines.push('export const comparison: unknown = undefined;');
    lines.push('');
  }

  if (opts.screenshotPaths && opts.screenshotPaths.length > 0) {
    lines.push(
      `export const screenshotPaths = ${JSON.stringify(opts.screenshotPaths)} as const;`,
    );
  } else {
    lines.push('export const screenshotPaths: string[] = [];');
  }

  lines.push('');
  return lines.join('\n');
}

async function main() {
  const {iteration, baseline, withScreenshots, dev} = parseArgs();
  const resultsDir = getResultsDir();
  const iterDir = path.join(resultsDir, iteration);
  const manifestPath = path.join(iterDir, 'manifest.json');

  if (!fs.existsSync(manifestPath)) {
    console.error(`No manifest.json found at ${manifestPath}`);
    process.exit(1);
  }

  const manifest = readJson(manifestPath);

  // Step 1: Ensure universal.json exists
  console.log('📊 Step 1: Ensuring evaluation data...');
  const iterationData = ensureUniversalJson(iteration);

  // Step 2: If baseline provided, ensure comparison
  let comparison: UniversalComparison | undefined;
  if (baseline) {
    console.log('📊 Step 2: Ensuring comparison data...');
    ensureUniversalJson(baseline);
    comparison = ensureComparison(iteration, baseline);
  }

  // Step 3: Collect screenshot paths
  let screenshotPaths: string[] = [];
  if (withScreenshots) {
    const screenshotsDir = path.join(iterDir, 'screenshots');
    if (fs.existsSync(screenshotsDir)) {
      screenshotPaths = fs
        .readdirSync(screenshotsDir)
        .filter(f => f.endsWith('.png'))
        .sort();
    }
  }

  // Step 4: Generate report data module
  console.log('📝 Step 3: Generating report data module...');
  const dataDir = path.join(APP_DIR, 'src', 'data');
  ensureDir(dataDir);

  const reportDataContent = generateReportData({
    iteration,
    iterationData,
    baseline,
    comparison,
    manifest,
    screenshotPaths,
  });

  fs.writeFileSync(path.join(dataDir, 'report-data.ts'), reportDataContent);
  console.log('  ✓ app/src/data/report-data.ts');

  // Step 5: Dev mode or build
  if (dev) {
    console.log('\n🚀 Starting Vite dev server...');
    const {createServer} = await import('vite');
    const server = await createServer({
      root: APP_DIR,
      server: {port: 5173, strictPort: true},
    });
    await server.listen();
    server.printUrls();
    console.log('\nOpen http://localhost:5173?mode=report to view the report.');
    console.log('Press Ctrl+C to stop.\n');
  } else {
    console.log('\n🏗️  Step 4: Building static report...');
    execSync('npx vite build', {
      cwd: APP_DIR,
      stdio: 'inherit',
    });

    // Copy built report to results dir
    const distDir = path.join(APP_DIR, 'dist');
    const reportHtml = path.join(distDir, 'index.html');
    if (fs.existsSync(reportHtml)) {
      const destPath = path.join(iterDir, 'report.html');
      fs.copyFileSync(reportHtml, destPath);
      console.log(`\n✅ Report saved to: ${destPath}`);
    } else {
      console.error('Build succeeded but no index.html found in dist/');
    }
  }
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
